### ISSUE TITLE
Negotiate method should return 406 if can't find relevant response negotiator

### ISSUE THREAD

**Issue by jchannon** [jchannon/Botwin#41]
Currently if you call `response.Negotiate(model)` and you ask for text/html and there is no negotiator that can handle html it will return json.  In this scenario it should return a 406 and empty body.

**Comment by jasonmitchell** [comment]
The specification for 406 (https://tools.ietf.org/html/rfc7231#section-6.5.6) says a payload with the available representations should be generated.  Should `Negotiate` be generating this to follow the spec or is returning an empty body a pragmatic choice?

**Comment by jchannon** [comment]
I think it's the latter and the same approach we used in Nancy but didn't realise the server SHOULD return a payload.  

I wonder if @darrelmiller has any opinion on this and what the body should look like

**Comment by jasonmitchell** [comment]
Personally I'm fine with the empty body.

If it was to generate a body, implementation-wise I guess `IResponseNegotiator` might need to expose the content type it will generate in order to build a list of available respresentations?

**Comment by darrelmiller** [comment]
@jchannon 
There was a draft proposal once upon a time that provided a way of describing the potential available variants, but I'm pretty sure it was all done in headers.  I suspect this 406 body is based on the same dream of returning a body from a 300.  However, until someone proposes a media type to do this and it gets some traction I think either an empty body, or some human readable HTML is the way to go.

On a related note.  Do you give the option for the server to say "I don't care that you asked for X, I don't support X, so I'm giving you the default Y"?  This is instead of doing 406.

**Comment by jchannon** [comment]
Yeah that's what it does now, if I can't find a way to negotiate the Accept header it returns a JSON representation. I know that it's ok to do that I just had a thought I wondered if 406 would be better. I'm in two minds 😄

**Comment by darrelmiller** [comment]
As a framework author, you get to have an opinion here.  Do you pick one way, or do you make it configurable?  The question is, what is a client going to do?  You are either returning an error code, or a content type they claim they can't handle.  The only upside to the second approach is a client can fallback to what a web browser does and say, would you like to save that to disk?
